/*
 * Swagger Blog
 *
 * Simple Blog
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type Body struct {
	Username string `json:"username,omitempty"`

	Content string `json:"content,omitempty"`
}
