/*
 * Swagger Blog
 *
 * Simple Blog
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type Comment struct {
	User string `json:"user,omitempty"`

	ArtitleId int64 `json:"artitle_id,omitempty"`

	Date string `json:"date,omitempty"`

	Cotent string `json:"cotent,omitempty"`
}
