/*
 * Swagger Blog
 *
 * Simple Blog
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/BlogByFourMan/Server/dal/db"
	"github.com/BlogByFourMan/Server/dal/model"
)

func ArticleIdCommentPost(w http.ResponseWriter, r *http.Request) {
	db.Init()

	var comment model.Comment

	err := json.NewDecoder(r.Body).Decode(&comment)

	if err != nil {
		Response(MyResponse{
			nil,
			err.Error(),
		}, w, http.StatusBadRequest)
	}

	articles := db.GetArticles(comment.ArticleId, 0)

	if len(articles) == 0 {
		Response(MyResponse{
			nil,
			"articles not found",
		}, w, http.StatusBadRequest)
	}

	for _, article := range articles {
		article.Comments = append(article.Comments, comment)
	}

	err = db.PutArticles(articles)

	if err != nil {
		Response(MyResponse{
			nil,
			err.Error(),
		}, w, http.StatusBadRequest)
	}

	Response(MyResponse{
		"comment add success",
		nil,
	}, w, http.StatusOK)
}

func UserLoginPost(w http.ResponseWriter, r *http.Request) {

	db.Init()

	var user model.User

	err := json.NewDecoder(r.Body).Decode(&user)

	if err != nil {
		Response(MyResponse{
			nil,
			"parameter error",
		}, w, http.StatusBadRequest)
	}

	check := db.GetUser(user.Username)

	if check.Username != user.Username || check.Password != user.Password {
		Response(MyResponse{
			nil,
			"username or password error",
		}, w, http.StatusBadRequest)
		return
	}

	Response(MyResponse{
		"log in success",
		nil,
	}, w, http.StatusOK)
}

func UserRegisterPost(w http.ResponseWriter, r *http.Request) {

	db.Init()

	var user model.User

	err := json.NewDecoder(r.Body).Decode(&user)
	r.ParseForm()
	value := r.Form
	fmt.Println(value)
	if err != nil {
		Response(MyResponse{
			nil,
			"parameter error",
		}, w, http.StatusBadRequest)
	}

	check := db.GetUser(user.Username)

	if check.Username != "" {
		Response(MyResponse{
			nil,
			"username existed",
		}, w, http.StatusBadRequest)
		return
	}

	err = db.PutUsers([]model.User{user})

	if err != nil {
		Response(MyResponse{
			nil,
			err.Error(),
		}, w, http.StatusBadRequest)
	}

	Response(MyResponse{
		"register success",
		"",
	}, w, http.StatusOK)

}
