/*
 * Swagger Blog
 *
 * Simple Blog
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Body2 struct {

	Username string `json:"username,omitempty"`

	Password string `json:"password,omitempty"`
}
