/*
 * Swagger Blog
 *
 * Simple Blog
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Artitle struct {

	Id int64 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Tags []Tag `json:"tags,omitempty"`

	Date string `json:"date,omitempty"`

	Cotent string `json:"cotent,omitempty"`
}
